#!/bin/bash
for file in "/home/student/Documents/wet3_files/Tools/example_IO_files/small.txt"
do
  for threads in {1..100}
  do
    ./GameOfLife $file 100 $threads n n
    echo $threads
  done
  echo "another file done"
done
